
name: Build and Published Docs to GitHub Pages

on:
  push:
    branches:
      - 'report-fix'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.19.0"

      - name: Install dependencies
        run: yarn install

      - name: Build docs
        run:  yarn workspace @embeddedchat/react build

      - name: Deploy Docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/react/docs